#repositories:
#- name: prometheus-community
#  url: https://prometheus-community.github.io/helm-charts

releases:
- name: ecom-db
  namespace: default
  chart: ./ecom-db-chart
  set:
  - name: rbac.create
    value: false

- name: ecom-app
  namespace: default
  chart: ./ecom-app-chart
  set:
  - name: rbac.create
    value: false

