apiVersion: v1
kind: Service
metadata:
  name: ecom-web-service  # Replace with your desired service name
spec:
  selector:
    app: ecom-web  # Matches the label in your deployment
  type: LoadBalancer  # Exposes the service to the internet
  ports:
  - port: 80  # Matches the container port (can be adjusted)
    targetPort: 80  # Forwards traffic to port 80 of the pods

